# Generated by Django 3.2.4 on 2021-06-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shopmodel_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopmodel',
            name='real_price',
            field=models.FloatField(default=0, verbose_name='real_price'),
        ),
    ]
