# Generated by Django 3.2.4 on 2021-06-26 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_shopcommentmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentmodel',
            options={'verbose_name': 'blog comment', 'verbose_name_plural': 'blog comments'},
        ),
        migrations.AlterModelOptions(
            name='shopcommentmodel',
            options={'verbose_name': 'shop comment', 'verbose_name_plural': 'shop comments'},
        ),
        migrations.RemoveField(
            model_name='commentmodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='commentmodel',
            name='name',
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='first_name',
            field=models.CharField(default=False, max_length=25, verbose_name='first_name'),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='last_name',
            field=models.CharField(default=False, max_length=25, verbose_name='last_name'),
        ),
    ]
