# Generated by Django 3.2.4 on 2021-06-26 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_auto_20210626_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='blog',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments', to='shops.blogmodel', verbose_name='blog'),
        ),
        migrations.AddField(
            model_name='shopcommentmodel',
            name='shop',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='shop_comments', to='shops.shopmodel', verbose_name='shop'),
        ),
    ]
