# Generated by Django 3.2.4 on 2021-06-19 10:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakermodel',
            name='about',
            field=ckeditor.fields.RichTextField(verbose_name='about'),
        ),
    ]
