# Generated by Django 3.2.4 on 2021-06-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_featuresmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuresmodel',
            name='real_price',
            field=models.FloatField(default=0, verbose_name='real_price'),
        ),
    ]
