# Generated by Django 3.2.4 on 2021-06-24 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_featuresmodel_real_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeaturesModel',
        ),
    ]
