# Generated by Django 3.2.4 on 2021-06-26 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_rename_commentmodel_speakercommentmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecommentmodel',
            options={'verbose_name': 'course comment', 'verbose_name_plural': 'courses comments'},
        ),
        migrations.AlterModelOptions(
            name='speakercommentmodel',
            options={'verbose_name': 'speaker comment', 'verbose_name_plural': 'speaker comments'},
        ),
    ]
